transmission:
    url: ENC[AES256_GCM,data:g+99B+c5SLdGgEzohHP0LZl15J8hkA==,iv:FQhOeOwzT44FX5jOSl7x85ape+ybUH4HnR3CaYwMULw=,tag:RrtadHZ+5turrkHmeV11Nw==,type:str]
    port: ENC[AES256_GCM,data:/clv,iv:iddvA/d6b7YIv3qCRWl1u5fgulvuG74UrPcC4QJz1TQ=,tag:K681Cj50X2Hj3x9CflRxSQ==,type:int]
    https: ENC[AES256_GCM,data:mO8Aog==,iv:zaDljYiPwtdRFwaxqwKr72esxM9Q6BXV2bf7Y6sQfXY=,tag:/rwVlgmJHy/od98OHz9GHg==,type:bool]
    user: ENC[AES256_GCM,data:SKN/jjk=,iv:t4XaDHj4QP9lULOo4PR17B2gN2/QHRie3N96uZ7celM=,tag:yNuODnXiYeY9k362MO5pzA==,type:str]
    password: ENC[AES256_GCM,data:Iv4+91Nzvl5U,iv:F+6K+RHShuRibQK2Vak6nDReGriZZnXzyOgYmvmWbnA=,tag:0cCKb1CLaoIH2vKhkQNa5Q==,type:str]
solarman:
    appId: ENC[AES256_GCM,data:8f4NiNJi4m19BP3pYI9ASg==,iv:OYi0OJT5UGesIMeQbVd3XujUFtq0e4f2+VtdBCtndi4=,tag:Dt4hi5VEZHx/rwdYE52+2w==,type:int]
    appSecret: ENC[AES256_GCM,data:7q1MsEG1RZh7tcgWTVTMmOWkFA4ymA1G4zZY+u4MicM=,iv:p5lpctKAVKfxo6fxD4an0mJq7yjwboV585PTHcCXsF0=,tag:xmT5i5xzfqIFRe9G8mYRiw==,type:str]
    email: ENC[AES256_GCM,data:lt8ssHNNvHZ3n947wH/RRg==,iv:AXNoeRirOSIoecwESEbDHf1HMFVy89K0jfMP311+8xM=,tag:+wf8h3xOdR05QuivS+pFnA==,type:str]
    password: ENC[AES256_GCM,data:pnLzfVkeLD1r9/gWpAucvrxd9kWnB5NIxf70Kmi0VwxqEidJeRSlTY9f/2idGSBkFWwigsIrqtWYTfBjjtdKHA==,iv:v+2r4JpWFUvdvss3GEGWr8uETU0PovBPFGYW3PuZjsU=,tag:SoI1k4f/7RKm+bW1j+fT/g==,type:str]
api:
    authURL: ENC[AES256_GCM,data:erW+zZ12T2GSIckNp4vQaZVjUURJUTW6WfFSWySbsASLU5JhdxjciljV5dGWaNBpIW33,iv:YCdts/YGBnthCBHfjlQfq3pTT+qIEq/AXE5j9sOlFP8=,tag:Q+bu760qPgOJRdJotNZ6cg==,type:str]
    apiURL: ENC[AES256_GCM,data:AoEaqtFSGsuA93vbz6yajqw/bxxpkbJ0x0NM0hXywBB8vMnUl6R3v3RmZBdaYEZ1dpfRRid0I8Q=,iv:dIpumS7TtLecmuhx0NBSgA4S5WfaklnNQnBvlyVYs7Y=,tag:F0rIkg99mvTQf7rlAiOCRg==,type:str]
telegram:
    botToken: ENC[AES256_GCM,data:j/4Z4Zg+yun+1JCMRh/O2JLuT4aE2kc4f1RCUm96YGdOKInk93A0ciF4+ENixg==,iv:HTZ+J2j/MeW9Evhx0WjR+rqtAT/6ctSG1+E8vY9LRZw=,tag:KoKl5F8pJv2XRG1tPSOaGg==,type:str]
    chatID: ENC[AES256_GCM,data:kKJ2YO1yEg==,iv:4rE6mz5+glU5Qn2vmWwprv/JharNMg+pymkQaQK2uj8=,tag:DGsQMSXpE4ej1D7/l3IerA==,type:int]
device:
    deviceSn: ENC[AES256_GCM,data:1ksaN4XSkK75XBiW,iv:rKYdJIVEABveH8uFYrs1WoFzld9SgX9r/ca1OQCtYjc=,tag:Fj06gbrirkCZyQCwleET1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-27T22:53:37Z"
    mac: ENC[AES256_GCM,data:h/6EuKK7f6Kl0yiFrfUZnBPrSUYUnp62BoVVPqwBWNrFg7R8lbOmx9F2xHC5vkLrgA7oLSVc0l5fYHaE/wSSFGbHyUvwph0XnRf8oZmQ0Vl6brnFB1DTVsh2vLhKkMdRhb4oXUdTFZvHJ/MhGOAXehv8AxGsc8V10sETHXGXPTM=,iv:Ba9vD+SXhtuhWs533K5P1lZbmD+2QEqxyjVDUWv3Gp8=,tag:uc54D58MgwOQQPYD5VXZXA==,type:str]
    pgp:
        - created_at: "2024-07-27T22:53:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4ljlkKz476VARAAw49HJRbHxdf1J+nyh4jcvUBy9C6/B6k97rV754wuYRn4
            Iu/PNBpZjmQ3aRy2a94/miX/cXRVrUy+m83oLq5Nsc7nbUInI7Ftfe6/XbZTMK1h
            MA8x16yrPKiULJ3Z07wEbanmEc6VWDiATzu8kBI+fijNPI7aep8nDKsy0AmRMa3L
            9I0psLz3toIikJO2Ql8nZ3O0yFju1veuen+pRTkEaDtzSSfwuMieRUIfGq42dCRr
            6AyXt8iDzmsKAfq+bhip2G69f6RwXrRfoKeuvIW4n3V1dcXEp5k4gcSEceMvA8wi
            JkFfQOeEyoaxzXMi7rI9/JYX+kIjgvhpxeDUHoIleX8uO0lq88Tw/Kzxgoe5WuXk
            EkOwJCa24k3F6qwjfTP6TgFNvsm6gaN87Yf2ysJ9oN28ouMgRWD7CRtlw7HjdFKZ
            hC5S/MFDVJvw9skTemwbC4sg9/iBMHxMjIGPZ4x7DUnnd0lqzDx9Nkt6LvTVCE3H
            FBDeNDGH2jPc8a29D99EShFPX2x3224Ux0s5maC+TC/91dU0721STAKTPaE7zeC2
            SK1WwjICbNSnOS5xXvoWg8kS91w1zP2YIT3uyA3ufmGY5vWgyXTXfKVuGQaomLpd
            /JucXt34hE57eGJle3NGGGtIx9wyJ3t4RLqHg1QDSfnP6/AWGX6lvvaKEuUL6MzU
            ZgEJAhDAt0rLLNwgJKV1IjEqmji/W5h6WlRYlUc+of34PR4En8KrEj2+5oc+a3O+
            85ythQqrGUk/oU3x2KJw5NqK7PzDY71kyaf1nVWJoSgkgEsfFKV9GOUv2HqxUrS8
            KJC+VBt+cw==
            =iAEu
            -----END PGP MESSAGE-----
          fp: A5BFC006D5A1400ABF637C3F5F6F8F6C408DE183
    unencrypted_suffix: _unencrypted
    version: 3.8.1
