transmission:
    url: ENC[AES256_GCM,data:Bf3iCa6Eqvy00m0RDP1H/GoK+blkBg==,iv:yMwn8CmK9PzObRX6xL3C2YgDaLafyCs/4M3UzRcnwyI=,tag:4Vo6Qilk6Qd2nQP9Q7Tc3g==,type:str]
    port: ENC[AES256_GCM,data:O8BJ,iv:229bPTnNYEVv3tHHBgxekF9y9EmTZWfds1in5xHYRGM=,tag:ytLERJbnsQJtBDuTMeReCQ==,type:int]
    user: ENC[AES256_GCM,data:NQ6SBOw=,iv:jDgPkDlK5164wx1hp1NGU2XPd+fsiG6ys6QiZ9AwxX8=,tag:V8DhDdJ+9YFNAd9iDTki4w==,type:str]
    password: ENC[AES256_GCM,data:oNaScMg7oOh7,iv:/HMsyUlxAFckB6ZCCpVqv8Da6TPoLrM17gDqH7L0ntU=,tag:hr9JQSNThuQhMRQ/UPoB2Q==,type:str]
solarman:
    appId: ENC[AES256_GCM,data:+0kuzX2oNy4zFUwy6VsQgg==,iv:y3jIBVwNw7DFIMBhkvtejoAeJIOc5yiQDbvB4NorBaw=,tag:cSH9in3gS+SoinIxkMS+hg==,type:int]
    appSecret: ENC[AES256_GCM,data:9RuzHXgKObkFbCvhzPTUTwnV6N8Nb0x2xbvgemqSPPE=,iv:Sp+lShsS9vrnKk5u8OoLm04VpmalFXDVKvBZPE0t2DU=,tag:5aL+85LbiDFpx/XKsAtbkA==,type:str]
    email: ENC[AES256_GCM,data:qmJX9Mevi29fShM8+LxBgg==,iv:aM6GvDFMeSr7gRhfuhK4eyLY13XG06EjSffrF9434u0=,tag:XUoxJYeoz9eApmELgE/nPA==,type:str]
    password: ENC[AES256_GCM,data:oGs1jd2dlPDpp3j0Xqu1Dm2p/sEQcBa6YQqb7Q/nB1xFjZzuX9qpr/opxaQbVC32qY3ewjMOj3ZypFA15e4uDg==,iv:4Vitun2nmonisNUvfo7DOJcknVblRzEYm3gxFZPxG8M=,tag:tGGdxRkjrXrXNI/OU5lpcw==,type:str]
api:
    authURL: ENC[AES256_GCM,data:241bJTmDjvdqGBHxTle/FyENywo9RRriWKq+Lpc2JzCWQr8hqDNVTMWe2E90b9jxGyBM,iv:kF+ygxwEx2SYxcJf+r7o4VNlqru19D1cwl0l5MXWcDs=,tag:q/JOEl1BvA5lCnsaqENvuA==,type:str]
    apiURL: ENC[AES256_GCM,data:WRyXytpCpKslX0uHl1Ajo4SHHMEMDzPcDD1FQK4lwCGTElY124U1kvvk9OC1mCILFkFX1adVmJs=,iv:j2ayYZtXWRFXYJJibzJkM1FvvMMg9+BVX/hsBSTSPRI=,tag:7uoKqa1PFOfpWnpdxlZBuQ==,type:str]
telegram:
    botToken: ENC[AES256_GCM,data:TADVa/m+cmdL/x5mokRXrixv9nTMYISVhL1Jgjbd3UVWY1PNMPJ/Lt659S6J7A==,iv:pbqTNhL+TYmmVPkzUJEPAkL5cv9zIHLXKhmlgWTHY5s=,tag:gIGHriQHZXNuBx9NoPi5VA==,type:str]
    chatID: ENC[AES256_GCM,data:LRC9ld5f8g==,iv:9LbfKLn0kng5IbdWswt1KxXex57vFN/0aXzXtujeJoQ=,tag:Dnb+aCQgvzJURxKsbFchjg==,type:int]
device:
    deviceSn: ENC[AES256_GCM,data:GcptBV6LFtQto7lJ,iv:Srcz3j/wEhAQdZKNPF80/3quZNPCn0E5hEJj5QopSf4=,tag:CA6HYjBHKTI9hRXM5YayZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-27T22:02:07Z"
    mac: ENC[AES256_GCM,data:XsjKqUg4ew/CepKMzqnz/2iePyhMSp3CbsE4eAodJfy4kBvPs8WsGB4izVvqdNdId272qzHSbFd9GgjdaUl4rgTUimxLxsSBvMIE0Fj/UnrrLqsnmSkWEJXqTh1OojwaqINzYmub4Z9iXuXowVAjgrWlWS8mQ6ws/Q2AA/XCk6k=,iv:4wFtUh2+q7pXe9KVANIz9vzbuNnlFHEUSu8PWEHytY4=,tag:Tct8nu/8ziUA7pM+kfaImQ==,type:str]
    pgp:
        - created_at: "2024-07-27T22:02:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4ljlkKz476VARAApvM8kxC/7suNH9kCVBLjU4PaGdGndYjJggFY1YyASK7M
            W9caMqUPyUHjMhdgbuFF/iPIn2fGgGQGozqCJ5QRptRsO/W0g8b/qfMD2l+aBkCl
            R/G7gWpBCZWr7ldRZgShbctQR02AXnWl+KvI0Gnt2lDXjP9o3MzYTELcVw0R1dQb
            s4RTcSZVzbyIgdUG1D2EI7L50kjBLtk/VaaJACzcKqKRyddu7/Eu6L7Yh3X2NQvh
            VXg4MSK3B6EghUQtSKzSRYI7s7MNP4svYHABOQDMeUVRuP9phxxkzCe93klaUpRZ
            OLqiAJKbQkxRzBru2m57qMmDrF0wURh+t68o8TTmijBVu98+XgA4CgyNMhj8x8NZ
            xV+4oc/7gNjyrP4zJOdTM1NyPg0p/SpKZmkgx0vn7DDcWq/MyPj0c4FrPgNi9TTM
            4NmXVG21REnOcgoiKYpAwpETEy2QE4ZbIGbVvfla9NbhoSa7SEhfi3UG1uVN+Bxq
            6ivkk9bl2Aeq+69TTeVTK6bc/1euUnhaugBv0Hsr4JphI2zRH+47A55XwQQPctyI
            SGkMOW/H8zrvJxYD2vmS9AupgRJxlZilN/yiwGaimqY3OxnJhLiVyAiOEFRJ7Q+V
            FZskf9s3m0v7+De2Y8PGfdX1mopTG325KXXw4z6MfPsq3sMcQqgXu4jB6QMFgbvU
            aAEJAhCd1gqqEPWPORnfUng5Ta/5GixzijsI80cz+iWoJBsa2/w/KgprdPZCKRR9
            qWlOfXO3jVmh+ZZcnuKnVLTrNEwpeXVqS8idf/qwx3pLT0eEr3JGYzic/kWzJWfL
            H6a8//3ojWi5
            =tqdZ
            -----END PGP MESSAGE-----
          fp: A5BFC006D5A1400ABF637C3F5F6F8F6C408DE183
    unencrypted_suffix: _unencrypted
    version: 3.8.1
